---
title: "Script"
author: "Karla Zarco"
date: "23/9/2022"
output: html_document
---

library(readr)
library(dplyr)
library(phyloseq)
library(ggplot2)
library(microbiome)
library(vegan)
library(hillR)
library(factoextra)
library(FactoMineR)
library(ALDEx2)
library(tibble)
library(readxl)
library(iNEXT)
library(xlsx)
library(tidyr)

setwd("C:/Users/karla/OneDrive/Documents/4_PARCELAS/barplot")
otu_data <- read_tsv("merged-table.tsv")
#otu_data <- read_tsv("merged-filtered-table.tsv")
tax_data <- read_tsv("merged_taxonomy_trained.tsv")
tax_data<- tax_data %>% 
  #separamos columna taxonomia en los diferentes niveles
  separate(Taxon, c("Kingdom", "Phylum", "Class","Order", "Family", "Genus","Specie"),  sep = ";")
tax_data<- tax_data[,1:8] 
sample_data <- read_tsv("metadata_trained.tsv",
                        col_types = "ccccccccc")

otu_data <- otu_data %>%
  tibble::column_to_rownames("OTU ID") 
tax_data <- tax_data %>% 
  tibble::column_to_rownames("OTU ID")
sample_data <- sample_data %>% 
  tibble::column_to_rownames("Sample ID")

#transformar en matrices 

otu_data <- as.matrix(otu_data)
tax_data <- as.matrix(tax_data)

#transformar en objetos phyloseq 
OTU = otu_table(otu_data, taxa_are_rows = TRUE)
TAX = tax_table(tax_data)
samples = sample_data(sample_data)


D0_D100_D100R<- phyloseq(OTU, TAX, samples)
filterPhyla = c(NA, "p__")
D0_D100_D100R<- subset_taxa(D0_D100_D100R, !Phylum %in% filterPhyla)
D0_D100_D100R_OTUTABLE<- otu_table(D0_D100_D100R)
D0_D100_D100R_OTU <- data.frame(D0_D100_D100R_OTUTABLE)
summary(sample_sums(D0_D100_D100R))